use wasm_bindgen::prelude::*;
use prost::Message;
use serde::Serialize;

// This includes the Rust code generated by prost from svga.proto.
// The actual name `com.opensource.svga.rs` is derived from the package statement
// in the .proto file: `package com.opensource.svga;`
// Dots are typically replaced with underscores by prost, but when including,
// we use the exact package name. Prost places the generated file directly in OUT_DIR.
pub mod svga_proto {
    include!(concat!(env!("OUT_DIR"), "/com.opensource.svga.rs"));
}

// Re-exporting generated types for easier use if needed, or use them directly via svga_proto::
use svga_proto::{MovieEntity, MovieParams as ProtoMovieParams, SpriteEntity as ProtoSpriteEntity, FrameEntity as ProtoFrameEntity, Layout as ProtoLayout, Transform as ProtoTransform, ShapeEntity as ProtoShapeEntity, AudioEntity as ProtoAudioEntity};
use svga_proto::shape_entity::{ShapeArgs as ProtoShapeArgs, RectArgs as ProtoRectArgs, EllipseArgs as ProtoEllipseArgs, ShapeType as ProtoShapeType};
use svga_proto::shape_entity::shape_style::{RgbaColor as ProtoRgbaColor, LineCap as ProtoLineCap, LineJoin as ProtoLineJoin};
use svga_proto::shape_entity::ShapeStyle as ProtoShapeStyle;


// Define output structures that mirror MovieEntity and its components,
// deriving Serialize for wasm-bindgen to convert to JS objects.
// These structs should be what the JavaScript side expects.

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Layout {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Transform {
    pub a: f32,
    pub b: f32,
    pub c: f32,
    pub d: f32,
    pub tx: f32,
    pub ty: f32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RgbaColor {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub enum LineCap {
    Butt = 0,
    Round = 1,
    Square = 2,
}

impl From<ProtoLineCap> for LineCap {
    fn from(cap: ProtoLineCap) -> Self {
        match cap {
            ProtoLineCap::Butt => LineCap::Butt,
            ProtoLineCap::Round => LineCap::Round,
            ProtoLineCap::Square => LineCap::Square,
        }
    }
}


#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub enum LineJoin {
    Miter = 0,
    Round = 1,
    Bevel = 2,
}

impl From<ProtoLineJoin> for LineJoin {
    fn from(join: ProtoLineJoin) -> Self {
        match join {
            ProtoLineJoin::Miter => LineJoin::Miter,
            ProtoLineJoin::Round => LineJoin::Round,
            ProtoLineJoin::Bevel => LineJoin::Bevel,
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ShapeStyle {
    pub fill: Option<RgbaColor>,
    pub stroke: Option<RgbaColor>,
    pub stroke_width: Option<f32>,
    pub line_cap: Option<LineCap>, // Prost enums are i32, convert if necessary
    pub line_join: Option<LineJoin>, // Prost enums are i32, convert if necessary
    pub miter_limit: Option<f32>,
    pub line_dash_i: Option<f32>,
    pub line_dash_ii: Option<f32>,
    pub line_dash_iii: Option<f32>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ShapeType {
    Shape = 0,
    Rect = 1,
    Ellipse = 2,
    Keep = 3,
}

impl From<ProtoShapeType> for ShapeType {
    fn from(shape_type: ProtoShapeType) -> Self {
        match shape_type {
            ProtoShapeType::Shape => ShapeType::Shape,
            ProtoShapeType::Rect => ShapeType::Rect,
            ProtoShapeType::Ellipse => ShapeType::Ellipse,
            ProtoShapeType::Keep => ShapeType::Keep,
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ShapeArgs {
    pub d: Option<String>, // For Shape
    pub x: Option<f32>, // For Rect and Ellipse
    pub y: Option<f32>, // For Rect and Ellipse
    pub width: Option<f32>, // For Rect
    pub height: Option<f32>, // For Rect
    pub corner_radius: Option<f32>, // For Rect
    pub radius_x: Option<f32>, // For Ellipse
    pub radius_y: Option<f32>, // For Ellipse
}


#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ShapeEntity {
    #[serde(rename = "type")]
    pub shape_type: Option<ShapeType>, // Prost enums are i32
    pub args: Option<ShapeArgs>, // Based on oneof in proto
    pub styles: Option<ShapeStyle>,
    pub transform: Option<Transform>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FrameEntity {
    pub alpha: f32,
    pub layout: Option<Layout>,
    pub transform: Option<Transform>,
    pub clip_path: Option<String>,
    pub shapes: Vec<ShapeEntity>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SpriteEntity {
    pub image_key: Option<String>,
    pub frames: Vec<FrameEntity>,
    pub matte_key: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AudioEntity {
    pub audio_key: Option<String>,
    pub start_frame: i32,
    pub end_frame: i32,
    pub start_time: i32,
    pub total_time: i32,
}


#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MovieParams {
    pub view_box_width: f32,
    pub view_box_height: f32,
    pub fps: i32,
    pub frames: i32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ParsedSvgaOutput {
    pub version: String,
    pub params: Option<MovieParams>,
    pub images: std::collections::HashMap<String, Vec<u8>>, // Using Vec<u8> for bytes
    pub sprites: Vec<SpriteEntity>,
    pub audios: Vec<AudioEntity>,
}

fn convert_proto_to_output(proto_movie: ProtoMovieEntity) -> ParsedSvgaOutput {
    let params = proto_movie.params.map(|p| MovieParams {
        view_box_width: p.view_box_width,
        view_box_height: p.view_box_height,
        fps: p.fps,
        frames: p.frames,
    });

    let mut images_map = std::collections::HashMap::new();
    for (key, value) in proto_movie.images {
        images_map.insert(key, value);
    }

    let sprites = proto_movie.sprites.into_iter().map(|s| SpriteEntity {
        image_key: s.image_key,
        frames: s.frames.into_iter().map(|f| FrameEntity {
            alpha: f.alpha,
            layout: f.layout.map(|l| Layout { x: l.x, y: l.y, width: l.width, height: l.height }),
            transform: f.transform.map(|t| Transform { a: t.a, b: t.b, c: t.c, d: t.d, tx: t.tx, ty: t.ty }),
            clip_path: f.clip_path,
            shapes: f.shapes.into_iter().map(|sh| {
                let mut s_args = ShapeArgs {
                    d: None, x: None, y: None, width: None, height: None,
                    corner_radius: None, radius_x: None, radius_y: None,
                };
                if let Some(args_oneof) = sh.args {
                    match args_oneof {
                        svga_proto::shape_entity::Args::Shape(a) => s_args.d = Some(a.d),
                        svga_proto::shape_entity::Args::Rect(a) => {
                            s_args.x = Some(a.x); s_args.y = Some(a.y);
                            s_args.width = Some(a.width); s_args.height = Some(a.height);
                            s_args.corner_radius = Some(a.corner_radius);
                        }
                        svga_proto::shape_entity::Args::Ellipse(a) => {
                            s_args.x = Some(a.x); s_args.y = Some(a.y);
                            s_args.radius_x = Some(a.radius_x); s_args.radius_y = Some(a.radius_y);
                        }
                    }
                }

                ShapeEntity {
                    shape_type: sh.r#type.and_then(|val| ProtoShapeType::try_from(val).ok().map(ShapeType::from)),
                    args: Some(s_args),
                    styles: sh.styles.map(|st| ShapeStyle {
                        fill: st.fill.map(|c| RgbaColor { r: c.r, g: c.g, b: c.b, a: c.a }),
                        stroke: st.stroke.map(|c| RgbaColor { r: c.r, g: c.g, b: c.b, a: c.a }),
                        stroke_width: Some(st.stroke_width),
                        line_cap: st.line_cap.and_then(|val| ProtoLineCap::try_from(val).ok().map(LineCap::from)),
                        line_join: st.line_join.and_then(|val| ProtoLineJoin::try_from(val).ok().map(LineJoin::from)),
                        miter_limit: Some(st.miter_limit),
                        line_dash_i: Some(st.line_dash_i),
                        line_dash_ii: Some(st.line_dash_ii),
                        line_dash_iii: Some(st.line_dash_iii),
                    }),
                    transform: sh.transform.map(|t| Transform { a: t.a, b: t.b, c: t.c, d: t.d, tx: t.tx, ty: t.ty }),
                }
            }).collect(),
        }).collect(),
        matte_key: s.matte_key,
    }).collect();

    let audios = proto_movie.audios.into_iter().map(|a| AudioEntity {
        audio_key: a.audio_key,
        start_frame: a.start_frame,
        end_frame: a.end_frame,
        start_time: a.start_time,
        total_time: a.total_time,
    }).collect();

    ParsedSvgaOutput {
        version: proto_movie.version,
        params,
        images: images_map,
        sprites,
        audios,
    }
}


#[wasm_bindgen]
pub fn parse_svga(binary_data: &[u8]) -> Result<JsValue, JsValue> {
    // Set up a panic hook for better error messages in WASM
    // Call this once in your application's entry point if you want to customize panic messages.
    // For a library, it's often better to let the consumer set this up.
    // console_error_panic_hook::set_once();

    match MovieEntity::decode(binary_data) {
        Ok(proto_movie) => {
            let output_struct = convert_proto_to_output(proto_movie);
            match serde_wasm_bindgen::to_value(&output_struct) {
                Ok(js_value) => Ok(js_value),
                Err(e) => Err(JsValue::from_str(&format!("Serialization error: {}", e))),
            }
        }
        Err(e) => Err(JsValue::from_str(&format!("Failed to decode SVGA data: {}", e))),
    }
}
