[package]
name = "svga_wasm_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92" # Using a recent version
prost = "0.12.6"
serde = { version = "1.0.203", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[build-dependencies]
prost-build = "0.12.6"

[profile.release]
lto = true
opt-level = 's' # Optimize for size
